# Configuración de Servidor Quarkus
quarkus.http.port=8080
quarkus.http.host=0.0.0.0

# Formato y nivel de registro en consola
quarkus.log.console.format=%d{yyyy-MM-dd HH:mm:ss} %-5p [%c{1.}] %s%e%n
quarkus.log.level=INFO
quarkus.log.category."com.evaluacion".level=INFO
